trigger:
- main

pool:
  name: default

steps:
- powershell: |
    $url = '<url>/rest/api/2/issue'
    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("username" + ":" + "password")))

    $headers = @{
        "Authorization" = "Basic $base64AuthInfo"
        "Content-Type" = "application/json"
    }

    $jira_summary = 'This is the issue summary'
    $jira_description = 'This is the issue description'

    $json_data = @"
    {
        "fields":{
            "project":{
                "key":"ABC"
            },
            "summary": "$jira_summary",
            "components":[
                {"name":"Component1"}
            ],
            "issuetype":{
                "name":"Story"
            },
            "description": "$jira_description"
        }
    }
    "@

    $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $json_data

    $parent_key = $response.key
    Write-Host "Created parent issue $parent_key"
  displayName: 'Create Jira Task'