trigger:
- main

pool:
  name: default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $JiraUrl = "https://your-jira-instance.atlassian.net/rest/api/2/issue/"
      $JiraUsername = "your-jira-username"
      $JiraToken = "your-jira-api-token"
        
        curl -X POST -H "Content-Type: application/json" -u "$username:$password" -d '{
        "fields": {
          "project": {
            "key": "SCRUM"
          },
          "summary": "Task Integration With Jira Title",
          "issuetype": {
            "name": "Task"
          }
        }
      }' https://cerqueradaniel.atlassian.net/rest/api/3/issue
      
  displayName: 'Create Jira Task'
