trigger:
- main

pool:
  name: default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      curl --request POST \
        --url 'https://your-domain.atlassian.net/rest/api/3/issue/archive' \
        --user 'email@example.com:<api_token>' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --data '{
        "jql": "project = FOO AND updated < -2y"
      }'

      
  displayName: 'Create Jira Task'
