trigger:
- main

pool:
  name: default

steps:
- script: |
    $JiraUrl = "https://cerqueradaniel.atlassian.net/"
    $JiraUsername = "your-jira-username"
    $JiraToken = "your-jira-api-token"

    $Headers = @{
        Authorization = "Bearer $JiraApiToken"
        ContentType = "application/json"
    }

    $RequestBody = @{
        fields = @{
            project = @{
                key = "YOURPROJECT"
            }
            summary = "Your task summary"
            description = "Your task description"
            issuetype = @{
                name = "Task"
            }
        }
    } | ConvertTo-Json

    $response = Invoke-RestMethod -Uri $JiraUrl -Headers $Headers -Method Post -Body $RequestBody

    Write-Host "Jira response:"
    $response
  displayName: 'Creación Task Jira'